version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/<your-db-name>
      - NEXT_PUBLIC_LIGHTHOUSE_API_KEY=<your_lighthouse_api_key>
      - MINTER_PRIVATE_KEY=<private_key_of_your_minter_wallet>
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=<db_username>
      - POSTGRES_PASSWORD=<db_password>
      - POSTGRES_DB=<your_db_name>
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: 